const objValues = {
  'Mary Cadogan': 5,
  'Sara Buenfeld': 6,
  'Barney Desmazery': 6,
  'James Martin': 3,
  'Angela Nilsen': 5,
  'Emma Lewis': 2,
  'Jane Hornby': 22,
  'Tom Kerridge': 2,
  'Good Food': 31,
  'Caroline Hire': 1,
  'Sarah Cook': 22,
  'Cassie Best': 21,
  'Nancy Birtwhistle': 1,
  'Sophie Godwin': 2,
  'Lesley Waters': 1,
  'Valerie Barrett': 2,
  'Lucy Netherton': 1,
  'Chelsie Collins': 4,
  'Juliet Sear': 1,
  'Lulu Grimes': 6,
  'Edd Kimber': 2,
  'Miriam Nice': 2,
  'Ruby Tandoh': 2,
  'John Torode': 1,
  'Rosie Birkett': 1,
  'Jennifer Joyce': 3,
  'BBC Good Food team': 1,
  'Alex Hollywood': 1,
  'Marcus Wareing': 1,
  'Gordon Ramsay': 1,
  'Justine Pattison': 2
}

const objEntries = {
  'Mary Cadogan': 5,
  'Sara Buenfeld': 6,
  'Barney Desmazery': 6,
  'James Martin': 3,
  'Angela Nilsen': 5,
  'Emma Lewis': 2,
  'Jane Hornby': 22,
  'Tom Kerridge': 2,
  'Good Food': 31,
  'Caroline Hire': 1,
  'Sarah Cook': 22,
  'Cassie Best': 21,
  'Nancy Birtwhistle': 1,
  'Sophie Godwin': 2,
  'Lesley Waters': 1,
  'Valerie Barrett': 2,
  'Lucy Netherton': 1,
  'Chelsie Collins': 4,
  'Juliet Sear': 1,
  'Lulu Grimes': 6,
  'Edd Kimber': 2,
  'Miriam Nice': 2,
  'Ruby Tandoh': 2,
  'John Torode': 1,
  'Rosie Birkett': 1,
  'Jennifer Joyce': 3,
  'BBC Good Food team': 1,
  'Alex Hollywood': 1,
  'Marcus Wareing': 1,
  'Gordon Ramsay': 1,
  'Justine Pattison': 2
}